version: '3.8'

services:

  mir4bot:
    build: '.'
    env_file:
        - .env     # path to your .env file
    command: python app/main.py
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/mir4_bot'
